title: Mj0ln1's Blog
description: "Mj0ln1r is a confident CTF player from Invaders"
author:
  name: "Mj0ln1"
  email: "playermj0ln1r@gmail.com"
  url: "https://themj0ln1r.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /posts/:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Mj0ln1r"
year : "2023"
social:
  name: Mj0ln1r
  email: PlayerMj0ln1r@gmail.com
  links:
    - https://twitter.com/TheMj0ln1r
    - https://github.com/TheMj0ln1r       
    - https://www.linkedin.com/in/mj0ln1r
